In [15]:
import torch
import torch.nn as nn
x =torch.rand(16,1,64,64)

In [16]:
x.shape

torch.Size([16, 1, 64, 64])

In [17]:
x1, x2 = torch.split(x, [0, 1], dim=1)

In [18]:
x1.shape

torch.Size([16, 0, 64, 64])

In [19]:
x2.shape

torch.Size([16, 1, 64, 64])

In [20]:
x1

tensor([], size=(16, 0, 64, 64))

In [21]:
x2

tensor([[[[7.3953e-01, 8.1835e-01, 7.6891e-01,  ..., 8.0221e-01,
           2.0160e-01, 9.0692e-01],
          [2.4276e-01, 5.2198e-01, 7.8718e-01,  ..., 8.4212e-01,
           1.2211e-01, 8.7436e-02],
          [3.0904e-02, 1.1786e-01, 2.7659e-01,  ..., 5.3051e-01,
           6.9987e-01, 1.3580e-01],
          ...,
          [8.2543e-01, 7.3429e-01, 4.9112e-01,  ..., 9.5380e-01,
           1.2902e-02, 9.1685e-01],
          [7.7283e-02, 8.5257e-01, 3.6195e-01,  ..., 9.4325e-01,
           6.3481e-01, 4.0082e-01],
          [9.1142e-01, 3.5236e-01, 6.0638e-01,  ..., 4.6093e-01,
           7.1428e-02, 7.1741e-01]]],


        [[[8.4267e-02, 1.0508e-01, 6.0407e-01,  ..., 1.7569e-01,
           5.8983e-01, 4.9797e-01],
          [8.1834e-01, 6.3553e-01, 7.6701e-01,  ..., 6.6803e-01,
           8.7036e-01, 9.0806e-01],
          [8.6501e-01, 9.6322e-01, 7.7360e-01,  ..., 1.4842e-01,
           6.9225e-01, 1.6500e-01],
          ...,
          [4.0561e-01, 1.1081e-01, 7.9198e-01,  ..., 4.96

In [22]:
input_dimension1=4
hidden_layer_channel = 64

cond_size1=16
condition_dimension = cond_size1

In [23]:
input_dimension1 // 2

2

In [41]:
x = torch.rand(16,4,64,64)

In [42]:
channel_part_1 = input_dimension1 // 2
channel_part_2 = input_dimension1 - input_dimension1 // 2

In [43]:
x1 = x.narrow(1, 0, channel_part_1)
x2 = x.narrow(1, channel_part_1, channel_part_2)

In [44]:
print(f"x.shape:{x.shape}, x1.shape:{x1.shape}, x2.shape:{x2.shape}") 

x.shape:torch.Size([16, 4, 64, 64]), x1.shape:torch.Size([16, 2, 64, 64]), x2.shape:torch.Size([16, 2, 64, 64])


In [45]:
def convolution_network(Hidden_layer):
    return lambda input_channel, output_channel: nn.Sequential(
        nn.Conv2d(input_channel, Hidden_layer, 3, padding=1),
        nn.ReLU(),
        nn.Conv2d(Hidden_layer, output_channel, 3, padding=1))

In [46]:
network_s_t = convolution_network(hidden_layer_channel)
s_t_network = network_s_t

In [47]:
s_net = s_t_network(channel_part_1 + condition_dimension, channel_part_1)
t_net = s_t_network(channel_part_2 + condition_dimension, channel_part_2)

In [48]:
s_net

Sequential(
  (0): Conv2d(18, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU()
  (2): Conv2d(64, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)

In [49]:
s = s_net(x2)

RuntimeError: Given groups=1, weight of size [64, 18, 3, 3], expected input[16, 2, 64, 64] to have 18 channels, but got 2 channels instead

In [50]:
x=torch.rand(1,4)

In [51]:
x

tensor([[0.5869, 0.8250, 0.6813, 0.1976]])

In [53]:
x1,x2 = torch.split(x,[0,1], dim=0)

In [54]:
x1

tensor([], size=(0, 4))

In [55]:
x2

tensor([[0.5869, 0.8250, 0.6813, 0.1976]])

In [56]:
c1 = torch.rand(2,4)
c1

tensor([[0.5410, 0.4163, 0.0791, 0.5004],
        [0.8403, 0.6147, 0.1964, 0.8843]])

In [59]:
x1_c = torch.cat([x1,c1],0)
x1_c

tensor([[0.5410, 0.4163, 0.0791, 0.5004],
        [0.8403, 0.6147, 0.1964, 0.8843]])